application: cloud-endpoints-example
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Endpoints handler
- url: /_ah/spi/.*
  script: sensors_v2.APPLICATION

libraries:
- name: pycrypto
  version: "2.6"

